#!/usr/bin/env bash
# leftwm theme up script

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

picom &

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

feh --bg-scale --no-fehbg ~/.config/wallpaper.jpg

dunst &

/usr/share/leftite/scripts/sys76-scheduler.py &

monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -n -q -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
    monitor=$monitors polybar leftwm &> /dev/null &
done