#!/usr/bin/env bash
# leftwm theme up script
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ -x "$(command -v picom)" ]; then
    picom &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

if [ -x "$(command -v feh)" ]; then
    feh --bg-scale --no-fehbg ~/.config/wallpaper.jpg
fi

if [ -x "$(command -v dunst)" ]; then
    dunst &
fi

monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -n -q -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
    monitor=$monitors polybar leftwm &> /dev/null &
done
